name: Build-DucQuyet-Dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          export THEOS=/opt/theos
          sudo git clone --recursive https://github.com/theos/theos.git $THEOS
          sudo chown -R $(id -u):$(id -g) $THEOS
          
          brew install ldid
          
          if [ ! -d "$THEOS/sdks" ]; then
            git clone https://github.com/theos/sdks.git $THEOS/sdks
          fi

      - name: Compile
        run: |
          export THEOS=/opt/theos
          # Tạo folder build_session thủ công để fix lỗi Clang
          mkdir -p .theos/obj
          touch .theos/build_session
          
          make clean
          # Chạy lệnh build chính thức
          make package FINALPACKAGE=1
        continue-on-error: true

      - name: Upload Dylib
        uses: actions/upload-artifact@v4
        with:
          name: DucQuyet-Menu-Dylib
          # Tìm file dylib ở mọi ngóc ngách trong folder .theos
          path: .theos/obj/**/*.dylib
