name: Build-DucQuyet-Dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          export THEOS=/opt/theos
          sudo git clone --recursive https://github.com/theos/theos.git $THEOS
          sudo chown -R $(id -u):$(id -g) $THEOS
          brew install ldid
          git clone https://github.com/theos/sdks.git $THEOS/sdks

      - name: Compile
        run: |
          export THEOS=/opt/theos
          mkdir -p .theos/obj
          touch .theos/build_session
          make clean
          # Build chỉ dylib để tránh lỗi stage của debian
          make DucQuyetMenu.all.tweak.variables FINALPACKAGE=1
        continue-on-error: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DucQuyet-Menu-Dylib
          # Tìm mọi file .dylib có trong các folder build
          path: |
            .theos/obj/arm64/*.dylib
            .theos/obj/arm64e/*.dylib
            .theos/obj/*.dylib
          if-no-files-found: error
