name: Build-DucQuyet-Dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          export THEOS=/opt/theos
          sudo rm -rf $THEOS
          # Tải Theos bản mới nhất
          sudo git clone https://github.com/theos/theos.git $THEOS
          cd $THEOS
          sudo git submodule update --init --recursive
          sudo chown -R $(id -u):$(id -g) $THEOS
          
          # Cài đặt công cụ ký file
          brew install ldid
          
          # Cài đặt SDK iOS (Sửa lỗi 128 bằng cách kiểm tra thư mục)
          if [ ! -d "$THEOS/sdks" ] || [ -z "$(ls -A $THEOS/sdks)" ]; then
            sudo rm -rf $THEOS/sdks
            git clone https://github.com/theos/sdks.git $THEOS/sdks
          fi

      - name: Compile
        run: |
          export THEOS=/opt/theos
          # Dọn dẹp bản build cũ
          make clean
          # Biên dịch cho iPhone đời thấp (arm64) và đời cao (arm64e)
          make DucQuyetMenu.all.tweak.variables FINALPACKAGE=1 ARCHS="arm64 arm64e"
        continue-on-error: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DucQuyet-Menu-Output
          path: |
            .theos/obj/arm64/*.dylib
            .theos/obj/arm64e/*.dylib
            .theos/obj/*.dylib
          if-no-files-found: error
