name: Build-DucQuyet-Dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          export THEOS=/opt/theos
          sudo git clone --recursive https://github.com/theos/theos.git $THEOS
          sudo chown -R $(id -u):$(id -g) $THEOS
          brew install ldid
          # Chỉ clone SDK nếu thư mục chưa tồn tại
          if [ ! -d "$THEOS/sdks" ]; then
            git clone https://github.com/theos/sdks.git $THEOS/sdks
          else
            echo "SDKs already exists, skipping clone."
          fi

      - name: Compile
        run: |
          export THEOS=/opt/theos
          # Xóa cache cũ để tránh lỗi biên dịch
          make clean
          # Lệnh build ép ra file dylib
          make DucQuyetMenu.all.tweak.variables FINALPACKAGE=1
        continue-on-error: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DucQuyet-Menu-Dylib
          path: |
            .theos/obj/arm64/*.dylib
            .theos/obj/arm64e/*.dylib
            .theos/obj/*.dylib
          if-no-files-found: error
