name: Build-DucQuyet-Dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          export THEOS=/opt/theos
          sudo rm -rf $THEOS
          sudo git clone https://github.com/theos/theos.git $THEOS
          cd $THEOS
          sudo git submodule update --init --recursive
          sudo chown -R $(id -u):$(id -g) $THEOS
          
          brew install ldid
          
          if [ ! -d "$THEOS/sdks" ] || [ -z "$(ls -A $THEOS/sdks)" ]; then
            sudo rm -rf $THEOS/sdks
            git clone https://github.com/theos/sdks.git $THEOS/sdks
          fi

      - name: Compile
        run: |
          export THEOS=/opt/theos
          # Lệnh quan trọng: Tạo thư mục .theos trước để tránh lỗi build_session
          mkdir -p .theos/obj
          touch .theos/build_session
          
          make clean
          # Sử dụng lệnh biên dịch tiêu chuẩn, ép kiến trúc arm64
          make package FINALPACKAGE=1 ARCHS="arm64 arm64e"
        continue-on-error: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DucQuyet-Menu-Output
          path: |
            .theos/obj/*.dylib
            packages/*.deb
          if-no-files-found: error
