name: Build-DucQuyet-Dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          export THEOS=/opt/theos
          sudo rm -rf $THEOS
          
          # Sử dụng --depth=1 để tải nhẹ hơn, tránh lỗi HTTP 500
          sudo git clone --depth=1 https://github.com/theos/theos.git $THEOS
          
          cd $THEOS
          # Tải submodule cũng với depth=1 để tối ưu dung lượng
          sudo git submodule update --init --recursive --depth=1
          sudo chown -R $(id -u):$(id -g) $THEOS
          
          brew install ldid
          
          # Cài đặt SDK
          if [ ! -d "$THEOS/sdks" ] || [ -z "$(ls -A $THEOS/sdks)" ]; then
            sudo rm -rf $THEOS/sdks
            git clone --depth=1 https://github.com/theos/sdks.git $THEOS/sdks
          fi

      - name: Compile
        run: |
          export THEOS=/opt/theos
          # Tạo môi trường build sạch
          mkdir -p .theos/obj
          touch .theos/build_session
          
          make clean
          # Ép kiến trúc arm64 cho iPhone
          make package FINALPACKAGE=1 ARCHS="arm64 arm64e"
        continue-on-error: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DucQuyet-Menu-Output
          path: |
            .theos/obj/*.dylib
            packages/*.deb
          if-no-files-found: error
