name: Build-DucQuyet-Dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          export THEOS=/opt/theos
          sudo git clone --recursive https://github.com/theos/theos.git $THEOS
          sudo chown -R $(id -u):$(id -g) $THEOS
          
          # Cài đặt ldid để ký tên (fix lỗi sign dylib)
          brew install ldid
          
          if [ ! -d "$THEOS/sdks" ]; then
            git clone https://github.com/theos/sdks.git $THEOS/sdks
          fi

      - name: Compile
        run: |
          export THEOS=/opt/theos
          make clean
          # Build dylib mà không bắt buộc phải đóng gói thành deb để tránh lỗi Stage
          make DucQuyetMenu.all.tweak.variables FINALPACKAGE=1
          
      - name: Upload Dylib
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: DucQuyet-Menu-Dylib
          path: .theos/obj/DucQuyetMenu.dylib
